
export const STUDENT_DETAILS_REQUEST_BEGINS: string = 'STUDENT_DETAILS_REQUEST_BEGINS';
export const STUDENT_DETAILS_REQUEST_SUCCESS: string = 'STUDENT_DETAILS_REQUEST_SUCCESS';
export const STUDENT_DETAILS_REQUEST_FAILED: string = 'STUDENT_DETAILS_REQUEST_FAILED';

export const STUDENT_LISTS_REQUEST_BEGINS: string = 'STUDENT_LISTS_REQUEST_BEGINS';
export const STUDENT_LISTS_REQUEST_SUCCESS: string = 'STUDENT_LISTS_REQUEST_SUCCESS';
export const STUDENT_LISTS_REQUEST_FAILED: string = 'STUDENT_LISTS_REQUEST_FAILED';

export const CLASSES_LISTS_REQUEST_BEGINS: string = 'CLASSES_LISTS_REQUEST_BEGINS';
export const CLASSES_LISTS_REQUEST_SUCCESS: string = 'CLASSES_LISTS_REQUEST_SUCCESS';
export const CLASSES_LISTS_REQUEST_FAILED: string = 'CLASSES_LISTS_REQUEST_FAILED';

export const SET_STUDENT_NAMES_MAPPED: string = 'SET_STUDENT_NAMES_MAPPED';
export const LOGOUT: string = 'LOGOUT';
